// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARhdccpENjMjxxwCHN6IRkNEY_L5A70HQ',
    appId: '1:24541519784:web:05848427b02fdd64b4879d',
    messagingSenderId: '24541519784',
    projectId: 'masgalon-8d72a',
    authDomain: 'masgalon-8d72a.firebaseapp.com',
    storageBucket: 'masgalon-8d72a.firebasestorage.app',
    measurementId: 'G-VFZTEQC345',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5drAyTB6R3dTNAjGQ3Fb_8eCvFxApv38',
    appId: '1:24541519784:android:f2c91c7d31fae331b4879d',
    messagingSenderId: '24541519784',
    projectId: 'masgalon-8d72a',
    storageBucket: 'masgalon-8d72a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFJJGP7pmPYNrTlAQVIh95pXGZzeb6hEc',
    appId: '1:24541519784:ios:de759ca1ee1c4ebbb4879d',
    messagingSenderId: '24541519784',
    projectId: 'masgalon-8d72a',
    storageBucket: 'masgalon-8d72a.firebasestorage.app',
    iosBundleId: 'com.example.pblAndroidMasgalonCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFJJGP7pmPYNrTlAQVIh95pXGZzeb6hEc',
    appId: '1:24541519784:ios:de759ca1ee1c4ebbb4879d',
    messagingSenderId: '24541519784',
    projectId: 'masgalon-8d72a',
    storageBucket: 'masgalon-8d72a.firebasestorage.app',
    iosBundleId: 'com.example.pblAndroidMasgalonCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARhdccpENjMjxxwCHN6IRkNEY_L5A70HQ',
    appId: '1:24541519784:web:d6d67adb4edfa9afb4879d',
    messagingSenderId: '24541519784',
    projectId: 'masgalon-8d72a',
    authDomain: 'masgalon-8d72a.firebaseapp.com',
    storageBucket: 'masgalon-8d72a.firebasestorage.app',
    measurementId: 'G-E850Z85DS3',
  );
}
